/**********************************************************************************
    Copyright (C) 2008 Investment Science Corp.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

***********************************************************************************/
#ifndef ALOGONDIALOG_H
#define ALOGONDIALOG_H
/*	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
aisdev/webide/alogondialog.h
														Logon Dialog

CHANGE HISTORY
Version	Date		Who		Change
1.0113	11/7/2006	tlw		Omit unused destructor.
1.0039	4/29/2004	tlw		Revise specification
												--------------- --------------
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

//	------------------------------------------------------ IMPORTS ------------------------------------------------------------
#include <QtGui/QDialog>
#include "ui_alogondialog.h"

//	------------------------------------------------ CLASS DECLARATIONS -------------------------------------------------------
/*!
\brief ALogonDialog provides a dialog that allows the user to enter a user name and a password.

\par Notes:
- The logon dialog layout is generated by Qt Designer.
 */

class ALogonDialog : public QDialog
{
    Q_OBJECT

public:
	ALogonDialog(QWidget* ipParent = NULL, const char* ipName = NULL, Qt::WFlags iFlgs = 0);

public:
	void	setValues(const QString& irUsrName, const QString& irPasswd);
	void	getValues(QString& orUsrName, QString& orPasswd);

private:
	Ui::ALogonDialogClass	cUi;
};

#endif // ALOGONDIALOG_H
